### ISSUE TITLE
Back Office - Images page is very slow

### ISSUE THREAD

**Issue by rjenks** [rjenks/Con-Org#104]

**Comment by JonathanNawrocki** [comment]
Just an update on this one... the actual "upload" portion works fairly well and quickly. However, things bog down when the image starts to load. Often I get complete page timeouts, but the action did complete. This happens on edits and on new.
I have been trying to clean up the system-wide images and file many pics away into the correct year. Updating the pulldown is fairly quick and painless unless I take too long and the page starts to load the image. Then, I am stuck for several minutes it seems.

**Comment by rjenks** [comment]
The server upgrade has resolved this issue.
