### ISSUE TITLE
What pages can show on the top horizontal  bar?

### ISSUE THREAD

**Issue by rawinans** [rjenks/Con-Org#150]
On the top horizontal bar, what are all the links for pages that can be seen?

Currenty WhoFest sees 6 of those, About us, contact us, Programming, Purchase, Guest and location.  Are there any more that we can  use?

**Comment by rjenks** [comment]
Currently, the following top level pages will be included in the NavBar if there they exist, aren't hidden, and the name is an exact match.
- Location
- Guests
- Programming
- Schedule
- Purchase
- Register
- About Us
- Contact Us

I am closing this issue as there is already an issue to make this customizable.  Issue #78
