### ISSUE TITLE
member export does not have email address

### ISSUE THREAD

**Issue by rawinans** [rjenks/Con-Org#153]
Would be great to have the member export report set to include the email address.  This would be helpful for  when we send out a Newsletter to the Masses.

**Comment by rjenks** [comment]
I added the following columns:
- EMail
- Login
- Organization
- Street
- Postal Code
- Phone
- Website
- Social Media Site
- Gender
- Announce List
- Vendor Announce

**Comment by rjenks** [comment]
Also note that you can use the Administration - Back Office - Announce feature to email your members or your entire mailing list.

**Comment by rawinans** [comment]
Yes but we have a fancy e-newsletter via mail chips or constant contact we
like to send out......

Robyn A Winans
Programming Chair
www.fencon.org
