### ISSUE TITLE
Can't merge two accounts when person has volunteered from both accounts

### ISSUE THREAD

**Issue by aislindsey** [rjenks/Con-Org#157]
I have a volunteer who has volunteered from multiple accounts and I can't merge the accounts. So can we either change the system so I can merge two volunteers? Or can we add a way to unvolunteer someone so we can then merge the accounts? Please? I love the Unicorn of Death, but I'm tired of killing the same unicorn over and over. Thanks!

**Comment by rjenks** [comment]
Merge Duplicates also doesn't merge the following:
- Panelist or Volunteer records
- Panel attendee (add to schedule feature)
- Department director or manager

**Comment by aislindsey** [comment]
Um. Minor new issue related to this. It sows the accounts as merged, but the volunteer still has two applications in according to the volunteer list.

**Comment by rjenks** [comment]
Ok, no problem.  I fixed that too.

**Comment by aislindsey** [comment]
I killed the unicorn again. It worked yesterday and then when I tried to do it today... dead unicorn. :(

**Comment by rjenks** [comment]
Fixed the new problem.
