### ISSUE TITLE
 Volunteer Form public

### ISSUE THREAD

**Issue by rawinans** [rjenks/Con-Org#160]
I didn't see a way to set the role on the page in the configuration.  WhoFest would like to set the Volunteer form as none instead of user.

**Comment by rjenks** [comment]
This would mean that they won't be signed in with an account and you wouldn't know who they are.  This is not likely to happen as the entire volunteering system is developed around user accounts.  Can you give more detail on why you want this?

**Comment by rawinans** [comment]
could the Volunter form be done such that public can see it like the
purchase page but when you go to submit the page it requires you to create
an account as  when you check with  the pruchase page.?

Robyn A Winans
Programming Chair
www.fencon.org

**Comment by rjenks** [comment]
What we do for AF is we hide the 'Volunteer Form' page and we have a page called 'Volunteer'.  The Volunteer page has general info about requirements and perks then gives them a link to the 'Volunteer Form' page.  When they go to the form, if they are not logged in then they are asked to log in or create an account.

Keep in mind that hiding a page does not block access or change the permissions required to view it.  It just doesn't show up on the menu.  This is useful for things like this.

**Comment by rawinans** [comment]
Ah.  Ok that makes sense.  I can rework that this evening.  Might be late
but could be helpful...

Robyn A Winans
Programming Chair
www.fencon.org

**Comment by rjenks** [comment]
I'm going to close this issue as I think what I suggested resolves the issue, but please comment if I am wrong.

**Comment by rawinans** [comment]
Good to close.

Robyn A Winans
Programming Chair
www.fencon.org
