### ISSUE TITLE
Email blast image tag

### ISSUE THREAD

**Issue by JonathanNawrocki** [rjenks/Con-Org#174]
According to Melissa Lum, the [image] tag will not resize properly for email blasts.
She is using the [img] tag instead.

I believe I previously read that the [image] tag should be the one she uses. Is this correct?
Is there a problem / limitation with the [img] in emails?

**Comment by JonathanNawrocki** [comment]
According to Melissa Lum 
"The [image] tag had not been working for the emails.  Nothing shows up when I use [image]  instead of [img]"

**Comment by rjenks** [comment]
[img] is the built-in tag in the bbcode library we are using.  I'm not sure I can change its behavior other than to rewrite it.  

The [image] tag is a custom tag I wrote. I made a change on issue #165 which added a CSS style of max-width:100%.  This means that no matter what width the image is or what the width was asked to be, that it will be no wider than the container it's in.  This means that as the browser narrows the image will shrink as necessary.

The biggest difference between the two tags is that [img] uses a URL to define the image and [image] uses the name of an image in the database.  I am tempted to fully remove [img] and require that images be uploaded, but I fear there are still cases where users may be required to refer to external images.

**Comment by rjenks** [comment]
Specifically, Melissa's problem was that she didn't understand the difference between the tags and tried to put a URL inside the [image] tag, which doesn't work.

**Comment by JonathanNawrocki** [comment]
I believe this issue is resolved. Rob, if you agree, I think we can just close this.

**Comment by rjenks** [comment]
Yes, this is resolved.
