### ISSUE TITLE
Kicking a Guest fro the Department of Guests causes a Unicorn Error

### ISSUE THREAD

**Issue by JonathanNawrocki** [rjenks/Con-Org#205]
Kicking a Guest fro the Department of Guests causes a Unicorn Error
![image](https://cloud.githubusercontent.com/assets/14830893/17348098/b2554a52-58d9-11e6-8e0c-a8b0ed5fe7ba.png)

**Comment by rjenks** [comment]
Resolved.

**Comment by rjenks** [comment]
It was trying to email the manager, but the department doesn't have a manager.  I added a check.  Originally the director and manager were required fields.  Somewhere along the line I made them not-required which has had some fallout damage.
