### ISSUE TITLE
Add an image browser

### ISSUE THREAD

**Issue by AF2016Lee** [rjenks/Con-Org#70]
Ideally, we'd a photo browser and search function on the Images page, but a link to the photos.animefest.org should be put there as a minimum. As someone new to the website back end, I was unaware of the separate domain (directory? whatever the first part of the address is called) with the pictures.

**Comment by rjenks** [comment]
photos.animefest.org is not part of Con Organizer.  However, you can already add a link to any external page onto almost any existing conorg page.  So in this case you can go to Back Office - Images and click the Edit Page icon in the upper right and add a link to photos.animefest.org.

However, it is desired that we have a better catalog of images that are stored in the conorg database (and accessed through BackOffice - Images).  We can track that feature request here.
