### ISSUE TITLE
Logging in on mobile

### ISSUE THREAD

**Issue by AF2016Lee** [rjenks/Con-Org#76]
I cannot figure out how to log in using my phone. (Samsung Galaxy S4) There is no login option on the menu, and going to a login-required page (like checkout) gives me the option to Create an Account but not to log in.

**Comment by rjenks** [comment]
You can login on mobile, but you have to scroll to see the login fields.  Click the hamburger icon (http://goo.gl/YLnrDU) which pulls up the menu.  Then swipe up in the black area to scroll down and reveal the login fields.

This wasn't an issue before, but with the number of top level pages increasing dramatically this has made this menu really tall.

This is NOT easily discoverable and needs to be fixed.  I am planning to collapse all of the menu items into a pulldown field.  That will keep the menu short and make the login fields visible regardless of the number of menu items.
