### ISSUE TITLE
Due Date on Invoices is Incorrect

### ISSUE THREAD

**Issue by rjenks** [rjenks/Con-Org#77]
It is showing a unix formatted date.

**Comment by rawinans** [comment]
Robert, Reviewed the data on open invoice for our vendors today and saw that the due date is the same as invoice date.

**Comment by rjenks** [comment]
Yes, it's tricky.  The problem is that in some cases 30 days could be after the con or after the catalog item should stop being sold.  For example, if you invoice someone for a $30 discounted membership for which the price increases to $35 in a couple of days then the invoice due date probably shouldn't be 30 days.  Since there can be many items on an invoice with different due dates this was causing my staff to complain about the due date being too late.  What would you think if I replaced the date with the text "upon receipt"?

**Comment by rawinans** [comment]
I think that would work for generalitys.   Most folks who purchase via the
website wouldn't need a due date as it would be the date of invoice.  Same
would be for paper membership.  As in WhoFest/FenCon our open invoices
would be mostly vendors.  And we certainly would like those paid before the
1st day of the convention.

Could due date of invoice be set up as a configurable field in the
Settings.  If I am waiting on a vendor payment.  I'll make a vendor
annoucement and remind folks they still have an open invoice that needs
payment.

Robyn A Winans
Programming Chair
www.fencon.org
