### ISSUE TITLE
Catalog item needs Quanity on hand/ Quanity sold

### ISSUE THREAD

**Issue by rawinans** [rjenks/Con-Org#86]
In the Catalog item there is a max Quanity field however i there needs to be read only fields such as quanity  on Hand or Quanity sold so we can determine we need to add to Max quanity or at least know how many are left to sell.  Logic needs to also be applied in the purchase area such that the user an't order more then what is on hand.  Also if invoices are voided then adjustments are made as necessary

**Comment by rjenks** [comment]
duplicate of issue #3
