### ISSUE TITLE
Allow for 5 types of members and 5 types of vendors

### ISSUE THREAD

**Issue by rjenks** [rjenks/Con-Org#93]
Currently the system has the **member**, **dealer** and **bazaar** roles.  Bazaar is too specific to AnimeFest and will likely only be used for this con.  This task is to add member2, member3, member4, member5, dealer2, dealer3, dealer4, and dealer5 roles and give them the same rights as the existing member and dealer roles.  Note that member and dealer **will not be** renamed to member1 and dealer1.

This will allow for conventions to support multiple membership types like Dealer Room vs Artist Alley and Member vs Premium Member.

**Comment by rjenks** [comment]
additional types have been added.

**Comment by rawinans** [comment]
Robert, on  3/13 we talk about adding a child2 to the member types.  Whofest would use this to different from Youth and Kid in tow membersihp's.    Wasn't for sure if you needed a new item and didn't want it to get lost.  Thanks

**Comment by rjenks** [comment]
I was working on a new page to help fix problems like this (issue #142 ), but I don't think I'm going to finish in time.  Therefore I went ahead and made the changes in the database.
